### ISSUE TITLE
can't create 

### ISSUE THREAD

**Issue by jeblister** [coderoad/coderoad-cli-deprecated#2]
Hi,

after i install the `coderoad-cli` i can't create a new dev project. I have this error :

```
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/coderoad-cli/setup/tutorial/tutorial.md'
```

**Comment by ShMcK** [comment]
Hi, sorry for the trouble. Let get this sorted out. A few questions:

Despite the error, does `coderoad create $NAME$` still generate a folder called `tutorial` with a `tutorial.md` inside ?

What is your OS?

**Comment by ShMcK** [comment]
I've updated the CLI to [`coderoad-cli@0.3.25`](https://github.com/coderoad/coderoad-cli/releases/tag/v0.3.25), but it may not have addressed your issue. 

As a backup, there is a simple work around that mimics `> coderoad create`

1) copy the files from [setup](https://github.com/coderoad/coderoad-cli/tree/master/setup)
2) change the "name" value in `package.json` to your projects name
3) run `> coderoad build`

OR

`> git clone https://github.com/coderoad/coderoad-functional-school`

**Comment by jeblister** [comment]
Thank you.

Yes the update of the CLI don't addressed the issue.

Instead, i use the first mimics solution.

**Comment by ShMcK** [comment]
I'd love to fix the issue for the future.

Could I get your:
- OS info
- node version (`node -v`)

**Comment by jeblister** [comment]
I work with OS X EL Capitan Version 10.11.3 
and
node 4.2.6

**Comment by ShMcK** [comment]
I found the issue. `setup` folder files were not included in the npm published package.

Adding `"files": ["setup", ...]` to the `package.json` file fixed the issue.
